suppressMessages({ library(oligo); library(pd.clariom.s.human); library(Biobase) })
options(warn=1)
base <- "${PROJECT_ROOT}"
logf <- file.path(base, "temp", "C1_preprocess4.log"); con <- file(logf, open="wt"); sink(con, type="output"); sink(con, type="message")
cat("start", format(Sys.time()), "mem=", memory.limit(), "\n"); flush(con)
rawdir <- file.path(base, "temp", "EMTAB9043_raw")
smap <- read.csv(file.path(base, "temp", "C1_emt9043_sample_map.csv"), stringsAsFactors=FALSE)
cel_files <- file.path(rawdir, smap$cel_file)
pd <- data.frame(sample=basename(cel_files), cell_line=smap$cell_line, stimulus=smap$stimulus, stringsAsFactors=FALSE)
rownames(pd) <- pd$sample
cat("reading all", length(cel_files), "\n"); flush(con)
es <- read.celfiles(cel_files, phenoData=new("AnnotatedDataFrame", data=pd))
cat("read done", dim(exprs(es)), format(Sys.time()), "\n"); flush(con)
saveRDS(es, file.path(base, "temp", "C1_raw_combined.rds"))
cat("saved_raw\n"); flush(con)
eset <- rma(es)
cat("RMA done", dim(exprs(eset)), format(Sys.time()), "\n"); flush(con)
saveRDS(eset, file.path(base, "temp", "C1_eset_rma.rds"))
write.csv(exprs(eset), file.path(base, "temp", "C1_expression_rma.csv"), quote=FALSE)
cat("ALL DONE\n"); flush(con)
sink(type="message"); sink(type="output"); close(con)
