suppressMessages({ library(oligo); library(pd.clariom.s.human); library(Biobase) })
options(warn=1)
base <- "${PROJECT_ROOT}"
logf <- file.path(base, "temp", "C1_preprocess2.log"); con <- file(logf, open="wt"); sink(con, type="output"); sink(con, type="message")
cat("start", format(Sys.time()), "\n"); flush(con)
rawdir <- file.path(base, "temp", "EMTAB9043_raw")
smap <- read.csv(file.path(base, "temp", "C1_emt9043_sample_map.csv"), stringsAsFactors=FALSE)
cel_files <- file.path(rawdir, smap$cel_file)
pd <- data.frame(sample=basename(cel_files), cell_line=smap$cell_line, stimulus=smap$stimulus, stringsAsFactors=FALSE)
rownames(pd) <- pd$sample
half <- ceiling(nrow(pd)/2)
cat("reading batch1 (", half, ")\n"); flush(con)
es1 <- read.celfiles(cel_files[1:half], phenoData=new("AnnotatedDataFrame", data=pd[1:half,,drop=FALSE]))
cat("batch1 done", dim(exprs(es1)), "\n"); flush(con)
es2 <- read.celfiles(cel_files[(half+1):nrow(pd)], phenoData=new("AnnotatedDataFrame", data=pd[(half+1):nrow(pd),,drop=FALSE]))
cat("batch2 done", dim(exprs(es2)), "\n"); flush(con)
# combine batches
es <- combine(es1, es2)
cat("combined dim", dim(exprs(es)), "\n"); flush(con)
saveRDS(es, file.path(base, "temp", "C1_raw_combined.rds"))
cat("saved raw combined\n"); flush(con)
cat("RMA start", format(Sys.time()), "\n"); flush(con)
eset <- rma(es)
cat("RMA done", dim(exprs(eset)), format(Sys.time()), "\n"); flush(con)
saveRDS(eset, file.path(base, "temp", "C1_eset_rma.rds"))
write.csv(exprs(eset), file.path(base, "temp", "C1_expression_rma.csv"), quote=FALSE)
cat("ALL DONE\n"); flush(con)
sink(type="message"); sink(type="output"); close(con)
